name: Deploy to IOT Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v3
       with:
         submodules: "recursive"
     - name: Initialize and Update Submodules
       run: |
          git submodule sync --recursive
          git submodule update --init --recursive
     - name: Make configure.sh executable
       run: chmod +x configure.sh
     - name: Configure
       run: ./configure.sh -c ${{ secrets.LORA_APP_KEY }} ${{ secrets.LORA_APP_EUI }}
     - name: Build
       run: make        
     - name: Push to server
       uses: easingthemes/ssh-deploy@v4.1.8

       env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ~/iot-folder/deploy-iot
       
       with:
           source: build/
           args: "-rlgoDzvc -i"
           SCRIPT_AFTER: |
              cd ~/iot-folder/
              ./flash-deployed-file.sh
