on:
  push:
    tags:
      - "v.*"
    branches:
      - "master"

name: Create Release

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: ncipollo/release-action@v1
        with:
          increment_pattern: '{version}'
          tag_regex: 'v(\d+\.\d+)'
          artifacts: "release.tar.gz,foo/*.txt"
