on:
  push:
    branches:
      - "master"

name: Create Release

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Generate release tag
      #   id: generate_release_tag
      #   uses: amitsingh-007/next-release-tag@v4.0.0
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     tag_prefix: "v"
      #     tag_template: "i.i"
      - name: Generate release tag
        id: generate_release_tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.generate_release_tag.outputs.new_tag }}
          artifacts: "release.tar.gz,foo/*.txt,*.hex"
