on:
  push:
    tags:
      - "v.*"
    branches:
      - "master"

name: Create Release

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Increment tag 
        uses: ncipollo/release-action@v1
        with:
          increment_pattern: '{version}'
          tag_regex: 'v(\d+\.\d+)'

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.increment_tag.outputs.new_tag }}
          artifacts: "release.tar.gz,foo/*.txt"
